name: Build

on:
    push:
        branches: "**" # push to any branch
    pull_request:
        branches: "**" # push to any branch

permissions:
    contents: read

jobs:
    test:
        strategy:
            matrix:
                python-version: ["3.12", "3.13", "3.14"]
        runs-on: ubuntu-latest

        name: Test application with Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  # Install a specific version of uv.
                  version: "0.9.22"
                  python-version: ${{ matrix.python-version }}
            - name: Installing dependencies
              run: uv sync --all-extras --dev

            - name: Installing the project
              run: uv pip install -e .

            - name: Run tests
              run: uv run pytest --doctest-modules test
